name: Publish Docker image 

on:
  push:
    branches:  
      - "main"  # main 分支有push时触发此 workflow
    tags:       # tag更新时触发此workflow
      - '*'
  pull_request:
    branches: [ "main" ]

# jobs:
#   build:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest
    
#     steps:  # 一个job由一个或多个step组成
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
jobs:  # workflow中的job

  push_to_registry:  # job的名字
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest   # job运行的基础环境

    steps:  # 一个job由一个或多个step组成
      - name: Check out the repo
        uses: actions/checkout@v3   # 官方的action，获取代码

      - name: Build and push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5.8 # docker build & push
        with:
          image: yourwit/all-url-uploader
          # 配置dockerhub的认证，在Github项目主页 【Settings】 -> 【Secrets】 添加对应变量 DOCKERHUB_USERNAME 和 DOCKERHUB_TOKEN
          username: ${{ secrets.DOCKERHUB_USERNAME }}  
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # https://hub.docker.com/settings/security 在这儿创建 token
          registry: docker.io

